Update scratchOrg-Sfdx.yml

diff --git a/.github/workflows/scratchOrg-Sfdx.yml b/.github/workflows/scratchOrg-Sfdx.yml
--- a/.github/workflows/scratchOrg-Sfdx.yml
+++ b/.github/workflows/scratchOrg-Sfdx.yml
@@ -26,10 +26,24 @@ jobs:
             # Checkout the source code
             - name: 'Checkout source code'
               uses: actions/checkout@v2
+              
+          # Store secret for dev hub
+            - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
+              shell: bash
+              run: |
+                  echo ${{ secrets.DEVHUB_SFDX_URL}} > ./GitLearning/DEVHUB_SFDX_URL.txt
+                  secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
+                  if [ $secretFileSize == 1 ]; then
+                      echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
+                  exit 1;
+                    fi
+            # Authenticate dev hub
+            - name: 'Authenticate Dev Hub'
+              run: sfdx auth:sfdxurl:store -f ./GitLearning/DEVHUB_SFDX_URL.txt -a devhub -d
 
             # Authenticate dev hub
             - name: 'Authenticate Dev Hub'
-              run: sfdx auth:sfdxurl:store -f ./GitLearning/DevHubTest.txt -a devhub -d
+              run: sfdx auth:sfdxurl:store -f ./GitLearning/DEVHUB_SFDX_URL.txt -a devhub -d
 
             # Create scratch org
             - name: 'Create scratch org'
