Update scratchOrg-Sfdx.yml

diff --git a/.github/workflows/scratchOrg-Sfdx.yml b/.github/workflows/scratchOrg-Sfdx.yml
--- a/.github/workflows/scratchOrg-Sfdx.yml
+++ b/.github/workflows/scratchOrg-Sfdx.yml
@@ -13,65 +13,65 @@ on:
 # Jobs to be executed
 jobs:
     scratch-org-test:
-    runs-on: ubuntu-latest
-    steps:
-        # Install Salesforce CLI
-        - name: 'Install Salesforce CLI'
-          run: |
-              wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
-              mkdir ~/sfdx
-              tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
-              echo "$HOME/sfdx/bin" >> $GITHUB_PATH
-              ~/sfdx/bin/sfdx version
-        # Checkout the source code
-        - name: 'Checkout source code'
-          uses: actions/checkout@v2
+        runs-on: ubuntu-latest
+        steps:
+            # Install Salesforce CLI
+            - name: 'Install Salesforce CLI'
+              run: |
+                  wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
+                  mkdir ~/sfdx
+                  tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
+                  echo "$HOME/sfdx/bin" >> $GITHUB_PATH
+                  ~/sfdx/bin/sfdx version
+            # Checkout the source code
+            - name: 'Checkout source code'
+              uses: actions/checkout@v2
 
-        # Store secret for dev hub
-        - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
-          shell: bash
-          run: |
-              echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt
-              secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
-              if [ $secretFileSize == 1 ]; then
-                  echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
-                  exit 1;
-              fi
-        # Authenticate dev hub
-        - name: 'Authenticate Dev Hub'
-          run: sfdx auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d
+            # Store secret for dev hub
+            - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
+              shell: bash
+              run: |
+                  echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt
+                  secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
+                  if [ $secretFileSize == 1 ]; then
+                      echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
+                      exit 1;
+                  fi
+            # Authenticate dev hub
+            - name: 'Authenticate Dev Hub'
+              run: sfdx auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d
 
-        # Create scratch org
-        - name: 'Create scratch org'
-          run: sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1
+            # Create scratch org
+            - name: 'Create scratch org'
+              run: sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1
 
-        # Deploy source to scratch org
-        - name: 'Push source to scratch org'
-          run: sfdx force:source:pushs
+            # Deploy source to scratch org
+            - name: 'Push source to scratch org'
+              run: sfdx force:source:pushs
 
-        # Assign permissionset
-        - name: 'Assign permissionset to default user'
-          run: sfdx force:user:permset:assign -n recipes
+            # Assign permissionset
+            - name: 'Assign permissionset to default user'
+              run: sfdx force:user:permset:assign -n recipes
 
-        # Import sample data
-        - name: 'Import sample data'
-          run: sfdx force:data:tree:import -p ./data/data-plan.json
+            # Import sample data
+            - name: 'Import sample data'
+              run: sfdx force:data:tree:import -p ./data/data-plan.json
 
-        # Run Apex tests in scratch org
-        - name: 'Run Apex tests'
-          run: sfdx force:apex:test:run -c -r human -d ./tests/apex -w 20
+            # Run Apex tests in scratch org
+            - name: 'Run Apex tests'
+              run: sfdx force:apex:test:run -c -r human -d ./tests/apex -w 20
 
-        # Delete temporary test file that Codecov is unable to parse
-        - name: 'Delete coverage file (temporary step)'
-          run: rm ./tests/apex/test-result-707*-codecoverage.json
+            # Delete temporary test file that Codecov is unable to parse
+            - name: 'Delete coverage file (temporary step)'
+              run: rm ./tests/apex/test-result-707*-codecoverage.json
 
-        # Upload code coverage data
-        - name: 'Upload code coverage for Apex to Codecov.io'
-          uses: codecov/codecov-action@v2.0.2
-          with:
-              flags: Apex
+            # Upload code coverage data
+            - name: 'Upload code coverage for Apex to Codecov.io'
+              uses: codecov/codecov-action@v2.0.2
+              with:
+                  flags: Apex
 
-        # Housekeeping
-        - name: 'Delete scratch org'
-          if: always()
-          run: sfdx force:org:delete -p -u scratch-org
+            # Housekeeping
+            - name: 'Delete scratch org'
+              if: always()
+              run: sfdx force:org:delete -p -u scratch-org
